Ak chris/authorisation page design
ahm-monash/evergreen pull request #209
Opened 2022-09-28 02:53 UTC by Akshith-Patil

Redesigned Authorisation Page

**What's new**
- New Landing page
- Styled the Login Card
- Redesigned styling for login success & error
- Design works on mobile view

Login Page
![Sign In Page](https://user-images.githubusercontent.com/81655881/192676557-dbdb9e09-bfa6-4909-93ac-f28e09426614.PNG)

Login Successful
![Successful Login](https://user-images.githubusercontent.com/81655881/192676588-31b7c0d3-8294-4d91-aaaf-aab3bb075f0a.PNG)

Login Error
![Login Error](https://user-images.githubusercontent.com/81655881/192676636-109b33a9-6e39-4ef9-be97-539241248ef4.PNG)

Mobile View
![image](https://user-images.githubusercontent.com/81655881/192676755-deb6b212-5cce-48b0-9a06-eb5c6bf90478.png)

2022-09-29 12:00 UTC, mt-empty requested changes
Well done.

I really like the art style, but I'm not sure if we can use it.
But, why is it uploaded twice?

If we are using the green plain one, why is the other one here?

2022-09-30 04:23 UTC, ChristianMarchetta commented on pages/signin.tsx
> +						md: '70.83%' // 5/12 + (1 - 5/12) * 1/2
They explain how the magic 70.83% is calculated

2022-09-30 10:19 UTC, mt-empty commented on pages/signin.tsx
> +						md: '70.83%' // 5/12 + (1 - 5/12) * 1/2
Its not clear why these numbers came from, what is 12?

2022-10-02 08:57 UTC, mt-empty approved these changes
This is how it look on a wide screen or any 21 by 9 ratio.
![image](https://user-images.githubusercontent.com/59728838/193446258-f206c0ee-16eb-47d7-aed6-d717215f2aba.png)

I'm not too fussed about it though, only a small percentage of users use widescreens, other than that LGTM, well cone.

Please merge #217 and the resolve conflics

2022-10-02 12:23 UTC, merged