New UI, Search functionality & Overall Percentage
ahm-monash/evergreen pull request #99
Opened 2022-07-30 02:03 UTC by Akshith-Patil

**New UI design Implemented along with Search Bar & Overall Green Percentage**
1. Added new colored icons for status.
2. Changed font style for all text
3. Summary section with overall & repo count
4. Search functionality
5. Updated the internal/external/users view with new icons & fonts. 
6. Created separate CSS file for each component

Header/Summary
![Summary   Header](https://user-images.githubusercontent.com/81655881/175812111-057d3df6-9184-400a-b5bf-abc666976ea5.PNG)

Table View
![Repo View](https://user-images.githubusercontent.com/81655881/175812129-86aa220e-410c-4783-995f-6732a122b0ae.PNG)

2022-07-30 06:45 UTC, reteppeter reviewed
Whilst each individual file looks fine, there needs to be an overall formatting pass (which could be done before merging) and refactoring (which shouldn't stop this from being merged; that's work for another sprint).

However, I don't agree with placing each pair of .tsx and .module.css files in their own folder - this just adds unnecessary clutter and takes up more room in a side bar, whilst not having any benefits for locality as two files with the same name but different extensions will be placed next to each other anyway.

2022-08-04 13:53 UTC, mt-empty requested changes
Good job guys,
I tested the GUI and the only thing that I found is:

Clicking on the question mark shows this:
![image](https://user-images.githubusercontent.com/59728838/182861076-db910f90-cab9-4441-a65a-206822b17c57.png)

My code review is not extensive, please ask someone to look at the code.

2022-08-04 13:53 UTC, mt-empty commented on components/SearchBar/SearchBar.tsx
> +          placeholder="Search Repository..."
Just `Search...` should be enough

2022-08-04 13:53 UTC, mt-empty commented on components/SummaryComponents/RepoOverviewTable/ReposOverviewTable.tsx
> +          <h3>Total Repos</h3>
either `Total` or `Total repositories`

2022-08-04 13:53 UTC, mt-empty commented on package-prev-commit.json
> +{
Please don't forget to remove this file before merging

2022-08-06 05:27 UTC, alexdelicato approved these changes

2022-08-06 05:43 UTC, mt-empty approved these changes

2022-08-06 05:45 UTC, merged